const RecipesActionsTypes = {
  FETCH_RECIPE_LIST: 'FETCH_RECIPE_LIST',
  RESET_RECIPE_LIST: 'RESET_RECIPE_LIST',
  GET_RECIPE: 'GET_RECIPE',
  CREATE_RECIPE: 'CREATE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
}

export default RecipesActionsTypes
