const ShoppingListActionsTypes = {
  ADD_SHOPPING_LIST_ITEM: 'ADD_SHOPPING_LIST_ITEM',
  REMOVE_SHOPPING_LIST_ITEM: 'REMOVE_SHOPPING_LIST_ITEM',
  UPDATE_SHOPPING_LIST_ITEM: 'UPDATE_SHOPPING_LIST_ITEM',

  START_EDIT_SHOPPING_LIST_ITEM: 'START_EDIT_SHOPPING_LIST_ITEM',
  RESET_EDITING_SHOPPING_LIST_ITEM: 'RESET_EDITING_SHOPPING_LIST_ITEM'
}

export default ShoppingListActionsTypes
