const RecipeInfoFormTypes = {
  CREATE_NEW_INGREDIENT: 'CREATE_NEW_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  UPDATE_INGREDIENT_VALUES: 'UPDATE_INGREDIENT_VALUES',
  VALIDATE_INGREDIENT_VALUES: 'VALIDATE_INGREDIENT_VALUES',
}

export default RecipeInfoFormTypes
