const RecipesActionsTypes = {
  CHANGE_RECIPE_CREATED_STATUS: 'CHANGE_RECIPE_CREATED_STATUS',
  CREATE_RECIPE_START: 'CREATE_RECIPE_START',
  CREATE_RECIPE_SUCCESS: 'CREATE_RECIPE_SUCCESS',
  CREATE_RECIPE_FAILURE: 'CREATE_RECIPE_FAILURE',
  FETCH_RECIPE_LIST_START: 'FETCH_RECIPE_LIST_START',
  FETCH_RECIPE_LIST_SUCCESS: 'FETCH_RECIPE_LIST_SUCCESS',
  FETCH_RECIPE_LIST_FAILURE: 'FETCH_RECIPE_LIST_FAILURE'
}

export default RecipesActionsTypes
