const RecipesActionsTypes = {
  CHANGE_RECIPE_CREATED_STATUS: 'CHANGE_RECIPE_CREATED_STATUS',
  CREATE_RECIPE_START: 'CREATE_RECIPE_START',
  CREATE_RECIPE_SUCCESS: 'CREATE_RECIPE_SUCCESS',
  CREATE_RECIPE_FAILURE: 'CREATE_RECIPE_FAILURE'
}

export default RecipesActionsTypes
