const RecipesActionsTypes = {
  CHANGE_RECIPE_CREATED_STATUS: 'CHANGE_RECIPE_CREATED_STATUS',
  CHANGE_RECIPE_REMOVED_STATUS: 'CHANGE_RECIPE_REMOVED_STATUS',
  CHANGE_RECIPE_UPDATED_STATUS: 'CHANGE_RECIPE_UPDATED_STATUS',
  CREATE_RECIPE_START: 'CREATE_RECIPE_START',
  CREATE_RECIPE_SUCCESS: 'CREATE_RECIPE_SUCCESS',
  CREATE_RECIPE_FAILURE: 'CREATE_RECIPE_FAILURE',
  FETCH_RECIPE_LIST_START: 'FETCH_RECIPE_LIST_START',
  FETCH_RECIPE_LIST_SUCCESS: 'FETCH_RECIPE_LIST_SUCCESS',
  FETCH_RECIPE_LIST_FAILURE: 'FETCH_RECIPE_LIST_FAILURE',
  REMOVE_RECIPE_START: 'REMOVE_RECIPE_START',
  REMOVE_RECIPE_SUCCESS: 'REMOVE_RECIPE_SUCCESS',
  REMOVE_RECIPE_FAILURE: 'REMOVE_RECIPE_FAILURE',
  UPDATE_RECIPE_START: 'UPDATE_RECIPE_START',
  UPDATE_RECIPE_SUCCESS: 'UPDATE_RECIPE_SUCCESS',
  UPDATE_RECIPE_FAILURE: 'UPDATE_RECIPE_FAILURE'
}

export default RecipesActionsTypes
