const UserActionsTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
  CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
  CHECK_USER_SESSION_FAILURE: 'CHECK_USER_SESSION_FAILURE',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  RESET_USER_ERRORS: 'RESET_USER_ERRORS'
}

export default Object.freeze(UserActionsTypes)
